version: 2.1

jobs:
  ci:
    machine:
      image: ubuntu-2204:current
    steps:
      - checkout
      - run: go version
      - run:
          name: ci
          command: go run ./main.go

workflows:
  ci:
    jobs:
      - ci
